apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
      affinity:
        nodeAffinity: {{- toYaml .Values.affinity.nodeAffinity | nindent 10 }}
        podAntiAffinity: {{- toYaml .Values.podAntiAffinity | nindent 10 }}
