apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      nodeSelector:
        pool: {{ .Values.nodeSelector.pool }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: nodejs-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          resources: {{- toYaml .Values.resources | nindent 12 }}
