apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejs-app
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
  type: {{ .Values.service.type }}
